#!/bin/bash
#
# MySpotIsHot Service Init
start() {
        initlog -c "echo -n Starting MySpotIsHot service: "
        sudo sh /home/krofek/myspotishot.sh &
        ### Create the lock file ###
        touch /var/lock/subsys/myspotishot
        success $"MySpotIsHot service startup"
        echo
}
#Service STOP func
stop() {
        initlog -c "echo -n Stopping MySpotIsHot service: "
        sudo killproc myspotishot
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/myspotishot
        echo
}
# JUST IN CASE ;)
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status myspotishot
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
